### ISSUE TITLE
Te package no contains Cosmos DB  library

### ISSUE THREAD

**Issue by danieldflrss** [nestjs/azure-database#366]
Te package no contains Cosmos DB  library only contents Table Storage library

**Comment by AndrewAllison** [comment]
I'm also getting
``` Module '"../../../node_modules/@nestjs/azure-database/dist"' has no exported member 'AzureCosmosDbModule'.

3 import { AzureCosmosDbModule } from '@nestjs/azure-database';
```

After a fresh npm install into a new nestjs project. 

Version `^1.0.0`

**Comment by AndrewAllison** [comment]
If it helps it looks like there is no folder for cosmos-db in the dist folder 
![image](https://user-images.githubusercontent.com/184729/110232400-56121b00-7f15-11eb-9366-800a2c180875.png)

**Comment by tomjdickson** [comment]
Yeah this is an issue - Doesn't contain Cosmos

**Comment by manekinekko** [comment]
This is duplicate of #238 

@kamilmysliwiec can you schedule a release of this package?

**Comment by kamilmysliwiec** [comment]
@manekinekko Just published

**Comment by manekinekko** [comment]
Yay! Thank you @kamilmysliwiec 🎉

Closing this issue for now.
