### ISSUE TITLE
Cannot find module '@nestjs/azure-database' or its corresponding type declarations.

### ISSUE THREAD

**Issue by danieldflrss** [nestjs/azure-database#376]
Cannot find module '@nestjs/azure-database' or its corresponding type declarations.

Installing version 2.0.0 from npm i --save @nestjs/azure-database

**Comment by lif9e1** [comment]
I can confirm the same issue. Thanks in advance for analyse and fixing.

**Comment by beneiltis** [comment]
I can confirm that too. You can switch to commit #c520eed089b91f6751bfa1507236270c860d8fab to fix that (at least to continue working).

Add this to your package.json:
`"@nestjs/azure-database": "git@github.com:nestjs/azure-database.git#c520eed089b91f6751bfa1507236270c860d8fab",`

**Comment by beneiltis** [comment]
I created a pull-request to fix this behavior. In the meantime you could use:
`"@nestjs/azure-database": "git@github.com:beneiltis/azure-database.git#27c180e929afa21cc12fe514d7932e655504428c"` in your package.json to continue with your work. (Fork including fix: https://github.com/beneiltis/azure-database)

**Comment by FedeMDO** [comment]
Yes, same error here. 
Please check @beneiltis 's PR #380

**Comment by RezaRahmati** [comment]
> I created a pull-request to fix this behavior. In the meantime you could use:
> `"@nestjs/azure-database": "git@github.com:beneiltis/azure-database.git#27c180e929afa21cc12fe514d7932e655504428c"` in your package.json to continue with your work. (Fork including fix: https://github.com/beneiltis/azure-database)

seems your PR has confict

**Comment by beneiltis** [comment]
solved :-)

**Comment by kamilmysliwiec** [comment]
Fixed
