### ISSUE TITLE
Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by codestellar** [nestjs/azure-database#512]
I'm submitting a security issue reported by Synk Scan
https://snyk.io/
It says Regular Expression Denial of Service (ReDoS)
introduced by @nestjs/azure-database@2.1.0 > azure-storage@2.10.4 > validator@9.4.1

## Expected behavior
There should not be a vulnerability. Need to update the validator package

**Comment by kamilmysliwiec** [comment]
Please, report this issue here https://github.com/Azure/azure-storage-node
